version: '3.8'

services:
  # POSTGRESQL - Banco de dados Desnormalizado
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  # RABBITMQ - FILAS
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  # LOCALSTACK - AWS
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566' # Porta para acessar todos os serviços do LocalStack
      - '4510:4510' # Porta específica para o DynamoDB
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - app-network

volumes:
  postgres_data:
  localstack_data:

networks:
  app-network:
    driver: bridge
